spring:
  application:
    name: mscartoes

server:
  port: 0 #sera gerado aleatorio (pratico para criar mais instancias da mesma aplicação)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #apontando onde esta eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} #estou nomeando a isntancia do meu mciroservico. Da forma que foi feito será criado nomes randomicos